### ISSUE TITLE
how to start?

### ISSUE THREAD

**Issue by The-Alchemist** [quauab/Weather#1]
Not sure how to start it...

I tried:
```
> node server.js
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND queueb
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```

**Comment by quauab** [comment]
I could not duplicate the same error message and was able to run without issue. I had downloaded the zip, extracted it, ran node server.js in and out of the directory where server.js lives. Try this -- change the server start code to this --> app.listen(3000);  According to the error description the server name 'queueb' can't be found and also make sure that the node application is accessible from anywhere on the system - the environment variable. Let me know what happens.
